version: "3.8"
services:
  app:
    build: .
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - sqltestdb

  sqltestdb:
    image: "mysql:latest"
    restart: always
    ports:
      - "3310:3306"
    environment:
      MYSQL_DATABASE: quiz
      MYSQL_USER: bogdan
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root